# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5efbc561a9f741e9159323c190d6d357e2658bef8734689dd0a3cffd075ca498f15fffb82d968c39c0f590d9a242b5d3eba27a5fc7fb4e57e6f40853028a9f

test:
  secret_key_base: 6c44c8600406e10618f60fd686713ae16f2a1f93d3cc0be409c2b575a8676991b8ab19126c83ecb63cc769c6ada16c7ca8e34adb133def89561bab1fcd65aaf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
